---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: env-bound-placement
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: environment
              operator: In
              values: ["prod"]